# -*- coding: utf-8 -*-
"""debate_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOm0w-rRJYCxd0P5IFaT4WxtdikR4sQ-
"""

from google.colab import drive
drive.mount('/content/drive')

from __future__ import annotations
import os
import re
import logging
from typing import Callable, List, Tuple, Dict, Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------
# Base class for debate agents
# ---------------------------
class DebateAgentBase:
    def __init__(self, role_name: str, llm_fn: Callable[[str], str] = None):
        self.role_name = role_name
        self.llm_fn = llm_fn or (lambda prompt: "LLM simulated response.")

    def propose(self, topic: str, context_pages: List[Tuple[str,int,str]]) -> str:
        raise NotImplementedError

    def rebut(self, other_statement: str, context_pages: List[Tuple[str,int,str]]) -> str:
        raise NotImplementedError

    def conclude(self, transcript: List[Tuple[str,str]]) -> str:
        raise NotImplementedError

# ---------------------------
# Pro-Innovation Agent
# ---------------------------
class DebateAgentA(DebateAgentBase):
    def __init__(self, llm_fn=None):
        super().__init__("Pro-Innovation Agent", llm_fn)

    def propose(self, topic, context_pages):
        context = "\n".join([f"[src: {src}, p.{p}] {t}" for src,p,t in context_pages])
        prompt = f"Argue for innovation-friendly regulation on: {topic}\nContext:\n{context}\nProvide 4 short bullet points with citations."
        return self.llm_fn(prompt)

    def rebut(self, other_statement, context_pages):
        context = "\n".join([f"[src: {src}, p.{p}] {t}" for src,p,t in context_pages])
        prompt = f"Rebut opposing points:\n{other_statement}\nContext:\n{context}"
        return self.llm_fn(prompt)

    def conclude(self, transcript):
        ttext = "\n".join([f"{role}: {stmt}" for role,stmt in transcript])
        prompt = f"Based on debate transcript, list 3 agreed principles and 2 disagreements.\nTranscript:\n{ttext}"
        return self.llm_fn(prompt)

# ---------------------------
# Precautionary Agent
# ---------------------------
class DebateAgentB(DebateAgentBase):
    def __init__(self, llm_fn=None):
        super().__init__("Precautionary Agent", llm_fn)

    def propose(self, topic, context_pages):
        context = "\n".join([f"[src: {src}, p.{p}] {t}" for src,p,t in context_pages])
        prompt = f"Argue for safety-first regulation on: {topic}\nContext:\n{context}\nProvide 4 short bullet points with citations."
        return self.llm_fn(prompt)

    def rebut(self, other_statement, context_pages):
        context = "\n".join([f"[src: {src}, p.{p}] {t}" for src,p,t in context_pages])
        prompt = f"Rebut opposing points:\n{other_statement}\nContext:\n{context}"
        return self.llm_fn(prompt)

    def conclude(self, transcript):
        ttext = "\n".join([f"{role}: {stmt}" for role,stmt in transcript])
        prompt = f"Based on debate transcript, list 3 agreed principles and 2 disagreements.\nTranscript:\n{ttext}"
        return self.llm_fn(prompt)

# ---------------------------
# Debate Orchestrator
# ---------------------------
def run_debate(agent_a, agent_b, topic, context_pages, rounds=2):
    transcript = []

    a_stmt = agent_a.propose(topic, context_pages)
    transcript.append((agent_a.role_name, a_stmt))

    b_stmt = agent_b.propose(topic, context_pages)
    transcript.append((agent_b.role_name, b_stmt))

    last_a, last_b = a_stmt, b_stmt
    for _ in range(rounds):
        b_reply = agent_b.rebut(last_a, context_pages)
        transcript.append((agent_b.role_name, b_reply))
        last_b = b_reply

        a_reply = agent_a.rebut(last_b, context_pages)
        transcript.append((agent_a.role_name, a_reply))
        last_a = a_reply

    a_conc = agent_a.conclude(transcript)
    b_conc = agent_b.conclude(transcript)
    transcript.append((f"{agent_a.role_name} - Conclusion", a_conc))
    transcript.append((f"{agent_b.role_name} - Conclusion", b_conc))

    consensus_points = _derive_consensus(a_conc, b_conc)

    return {
        "transcript": transcript,
        "conclusion_a": a_conc,
        "conclusion_b": b_conc,
        "consensus": consensus_points,
    }

def _derive_consensus(text_a, text_b):
    tokens_a = set(re.findall(r"\b\w{4,}\b", text_a.lower()))
    tokens_b = set(re.findall(r"\b\w{4,}\b", text_b.lower()))
    overlap = sorted(tokens_a & tokens_b)
    return overlap[:6]

def run_debate_and_save(agent_a, agent_b, context_pages, topic, output_path):
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    result = run_debate(agent_a, agent_b, topic, context_pages)

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(f"Policy Debate Brief - Topic: {topic}\n\n")
        fh.write("--- TRANSCRIPT ---\n")
        for role, stmt in result["transcript"]:
            fh.write(f"{role}:\n{stmt}\n\n")
        fh.write("--- CONSENSUS ---\n")
        for p in result["consensus"]:
            fh.write(f"- {p}\n")
        fh.write("\n--- CONCLUSIONS ---\n")
        fh.write(f"{agent_a.role_name}:\n{result['conclusion_a']}\n\n")
        fh.write(f"{agent_b.role_name}:\n{result['conclusion_b']}\n")

    logger.info("Debate saved to %s", output_path)

    # Print output on console
    print(f"Debate saved to {output_path}")
    print("\n--- TRANSCRIPT ---")
    for role, stmt in result["transcript"]:
        print(f"{role}:\n{stmt}\n")
    print("--- CONSENSUS ---")
    for p in result["consensus"]:
        print(f"- {p}")
    print("\n--- CONCLUSIONS ---")
    print(f"{agent_a.role_name}:\n{result['conclusion_a']}\n")
    print(f"{agent_b.role_name}:\n{result['conclusion_b']}\n")

    return result

# ---------------------------
# Demo execution
# ---------------------------
if __name__ == "__main__":
    example_pages = [
        ("ac8b3538-en.pdf", 1, "OECD Employment Outlook 2024 discusses net-zero transition and labor demand."),
        ("ch1.pdf", 2, "IMF projections for global GDP growth in 2025 and regional differences."),
    ]
    a = DebateAgentA()
    b = DebateAgentB()
    run_debate_and_save(
        a,
        b,
        context_pages=example_pages,
        topic="OECD Employment Outlook 2024",
        output_path="/content/drive/MyDrive/results/final_policy_brief.txt"
    )