# -*- coding: utf-8 -*-
"""memory_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIlsN-PUMxsv0L-CB7je3BkoNp_mjVrx
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import json
import time
from typing import Any, Dict, Optional, Tuple
import numpy as np
import pandas as pd
import os

# مسیر ذخیره
RESULTS_DIR = Path("/content/drive/MyDrive/results")
MEMORY_PATH = RESULTS_DIR / "memory.json"
METRICS_PATH = RESULTS_DIR / "metrics.json"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

class MemoryAgent:
    """Stores parameter records and offers simple auto-tuning."""

    def __init__(self, memory_path: Path = MEMORY_PATH) -> None:
        self.memory_path = memory_path
        if not self.memory_path.exists():
            self._write({"records": []})

    def _read(self) -> Dict[str, Any]:
        if not self.memory_path.exists() or self.memory_path.stat().st_size == 0:
            return {"records": []}
        with self.memory_path.open("r", encoding="utf-8") as fh:
            try:
                return json.load(fh)
            except json.JSONDecodeError:
                return {"records": []}

    def _write(self, obj: Dict[str, Any]) -> None:
        with self.memory_path.open("w", encoding="utf-8") as fh:
            json.dump(obj, fh, ensure_ascii=False, indent=2)

    def log(
        self,
        alpha: float,
        k: float,
        latency: Optional[float],
        confidence: Optional[float],
        beta: Optional[float] = None,
        extra: Optional[Dict[str, Any]] = None,
    ) -> None:
        memory = self._read()
        rec = {
            "ts": time.time(),
            "alpha": float(alpha),
            "k": float(k),
            "latency": None if latency is None else float(latency),
            "confidence": None if confidence is None else float(confidence),
            "beta": None if beta is None else float(beta),
            "extra": extra or {},
        }
        memory.setdefault("records", []).append(rec)
        self._write(memory)

    def get_records_df(self) -> pd.DataFrame:
        memory = self._read()
        records = memory.get("records", [])
        if not records:
            return pd.DataFrame(columns=["ts", "alpha", "k", "latency", "confidence", "beta"])
        df = pd.DataFrame(records)
        df["ts"] = pd.to_datetime(df["ts"], unit="s")
        return df

    def _load_metrics(self) -> Dict[str, Any]:
        if not METRICS_PATH.exists() or METRICS_PATH.stat().st_size == 0:
            return {}
        with METRICS_PATH.open("r", encoding="utf-8") as fh:
            try:
                return json.load(fh)
            except json.JSONDecodeError:
                return {}

    def auto_tune(
        self,
        target_metric: str = "factual_precision",
        alpha_bounds: Tuple[float, float] = (0.0, 1.0),
        k_bounds: Tuple[float, float] = (0.0, 1.0),
        beta_bounds: Tuple[float, float] = (0.0, 1.0),
        grid_steps: int = 5,
    ) -> Dict[str, float]:
        df = self.get_records_df()
        metrics = self._load_metrics()

        if df.empty:
            return {
                "alpha": (alpha_bounds[0] + alpha_bounds[1]) / 2.0,
                "k": (k_bounds[0] + k_bounds[1]) / 2.0,
                "beta": (beta_bounds[0] + beta_bounds[1]) / 2.0,
            }

        # fallback: استفاده از confidence در صورت نبود metric
        hist_points = df[["alpha", "k", "beta"]].fillna(0.0).values
        hist_scores = df["confidence"].fillna(0.0).values if "confidence" in df.columns else np.zeros(len(df))

        alphas = np.linspace(alpha_bounds[0], alpha_bounds[1], grid_steps)
        ks = np.linspace(k_bounds[0], k_bounds[1], grid_steps)
        betas = np.linspace(beta_bounds[0], beta_bounds[1], grid_steps)

        best = None
        best_score = -np.inf

        for a in alphas:
            for k in ks:
                for b in betas:
                    cand = np.array([a, k, b], dtype=float)
                    dists = np.linalg.norm(hist_points - cand, axis=1)
                    weights = 1.0 / (dists + 1e-6)
                    weighted_sum = np.sum(weights * hist_scores)
                    score = weighted_sum / np.sum(weights)
                    if score > best_score:
                        best_score = float(score)
                        best = {"alpha": float(a), "k": float(k), "beta": float(b)}

        # log خودکار پارامتر پیشنهادی
        self.log(alpha=best["alpha"], k=best["k"], latency=None, confidence=best_score, beta=best["beta"], extra={"auto_tune_recommendation": True})
        return best

# ---------- Demo اجرا ----------
if __name__ == "__main__":
    ma = MemoryAgent()

    # log چند نمونه داده
    ma.log(alpha=0.3, k=0.7, latency=0.12, confidence=0.75)
    ma.log(alpha=0.5, k=0.5, latency=0.10, confidence=0.78)
    ma.log(alpha=0.6, k=0.4, latency=0.15, confidence=0.80)

    # اجرای auto-tune
    rec = ma.auto_tune(grid_steps=5)
    print("Auto-tune recommendation:", rec)
    print("Memory saved to:", MEMORY_PATH)