# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfWDm5ZlUeO3rph8d18Toko_eAQzoZk2
"""

# 1. Install required libraries
!pip install pdfplumber langchain spacy
!python -m spacy download en_core_web_sm

# 2. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import os
import pdfplumber
from typing import List


# Please set this variable to the exact path where your files are located
DATA_DIR = "/content/drive/MyDrive/data"

# Make sure the directory exists
if not os.path.exists(DATA_DIR):
    print(f"❌ CRITICAL ERROR: Directory does not exist: {DATA_DIR}")
    pdf_files = []  # Initialize as empty list if directory doesn't exist
else:
    print(f"✅ Directory exists: {DATA_DIR}")

    # 1. Find all PDF files in that directory
    pdf_files = [os.path.join(DATA_DIR, f) for f in os.listdir(DATA_DIR) if f.lower().endswith(".pdf")]

    if not pdf_files:
        print("❌ ERROR: No PDF files found using os.listdir. Check file names or Drive mount.")
    else:
        print(f"✅ FOUND {len(pdf_files)} PDF files.")

        # 2. Try reading the first file with pdfplumber
        first_pdf_path = pdf_files[0]
        print(f"Attempting to read the first file: {os.path.basename(first_pdf_path)}")

        try:
            with pdfplumber.open(first_pdf_path) as pdf:
                # Extract text from the first page for testing
                first_page_text = pdf.pages[0].extract_text()

            print("\n🎉 SUCCESS! File reading successful.")
            print("--- Extracted text snippet (First 150 chars) ---")
            print(first_page_text[:150] + "...")
            print("-------------------------------------------------")

            # If we reached here, the path and tools are working correctly
            print("Now we can proceed with the full Ingestion Agent logic.")

        except Exception as e:
            print(f"\n❌ FATAL ERROR in pdfplumber.open: Could not read the file.")
            print(f"Reason: {e}")
            print("Possible fix: Disconnect and remount Google Drive.")

# src/agents/pdf_ingestion_agent.py (Logic implemented as a class in Colab)
import os
import pdfplumber
from typing import List, Dict, Any
from langchain.text_splitter import RecursiveCharacterTextSplitter

class PDFIngestionAgent:
    """
    Agent responsible for loading, extracting text/tables from PDFs,
    and performing semantic chunking.
    """
    def __init__(self, chunk_size: int = 1000, chunk_overlap: int = 200):
        """Initializes the agent with chunking parameters."""
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.text_splitter = RecursiveCharacterTextSplitter(
            separators=["\n\n\n", "\n\n", "\n", " ", ""],
            chunk_size=self.chunk_size,
            chunk_overlap=self.chunk_overlap,
            length_function=len,
        )

    def _extract_and_chunk(self, pdf_path: str) -> List[Dict[str, Any]]:
        """Extracts text from a single PDF and splits it into chunks."""
        full_text = ""
        try:
            with pdfplumber.open(pdf_path) as pdf:
                for page in pdf.pages:
                    # Use keep_layout=True for better table/structure extraction
                    text = page.extract_text(x_tolerance=2, keep_layout=True)
                    if text:
                        # Add a separator to maintain semantic boundary
                        full_text += text + "\n\n---\n\n"
        except Exception as e:
            print(f"Error reading {pdf_path}: {e}")
            return []

        # Create LangChain documents/chunks
        chunks = self.text_splitter.create_documents([full_text])

        # Prepare structured output
        file_name = os.path.basename(pdf_path)
        chunk_list = []
        for i, chunk in enumerate(chunks):
            chunk_list.append({
                "original_text": chunk.page_content.replace("\n\n---\n\n", " "),
                "metadata": {
                    "source_file": file_name,
                    "chunk_id": f"{file_name}_{i}",
                    "chunk_index": i
                }
            })
        return chunk_list

    def ingest_pdfs(self, data_dir: str) -> List[Dict[str, Any]]:
        """Processes all PDFs in the specified directory."""
        all_chunks = []
        if not os.path.exists(data_dir):
            print(f"❌ Error: Data directory does not exist: {data_dir}")
            return []

        pdf_files = [os.path.join(data_dir, f) for f in os.listdir(data_dir) if f.endswith(".pdf")]

        if not pdf_files:
            print(f"Warning: No PDF files found in {data_dir}.")
            return []

        print(f"\n[IngestionAgent] Ingesting {len(pdf_files)} PDF files...")
        for pdf_path in pdf_files:
            print(f"  > Processing: {os.path.basename(pdf_path)}")
            chunks = self._extract_and_chunk(pdf_path)
            all_chunks.extend(chunks)

        print(f"[IngestionAgent] Total chunks created: {len(all_chunks)}")
        return all_chunks

