# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHPWeO0rdjQggCr5sVI03YJXBxOzQfLq
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline
from huggingface_hub import login
from tqdm import tqdm

# -------------------------------
# Paths
# -------------------------------
RETRIEVED_DOCS_PATH = "/content/drive/MyDrive/results/retrieval_ablation.json"
OUTPUT_PATH = "/content/drive/MyDrive/results/rag_qa_results.json"

# -------------------------------
# Hyperparameters
# -------------------------------
MAX_CHUNK_TOKENS = 500      # max tokens per chunk
MAX_DOCS = 5                # max number of retrieved documents to use
MODEL_NAME = "google/flan-t5-base"  # Changed to a publicly available model
DEVICE = "cpu"              # "cuda" if GPU available
MAX_NEW_TOKENS = 256

# -------------------------------
# Hugging Face authentication
# -------------------------------
HF_TOKEN = ""
login(token=HF_TOKEN)

# -------------------------------
# Load retrieved documents (Task 3)
# -------------------------------
with open(RETRIEVED_DOCS_PATH, "r", encoding="utf-8") as f:
    retrieved_data = json.load(f)

docs = [item["text"] for item in retrieved_data["retrieval_results"]]
print(f"✅ Loaded {len(docs)} retrieved documents.")

# -------------------------------
# Initialize model and pipeline
# -------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_auth_token=HF_TOKEN)
model = AutoModelForSeq2SeqLM.from_pretrained( # Changed to AutoModelForSeq2SeqLM
    MODEL_NAME,
    device_map={"": "cpu"},   # Change to {"": "cuda"} if GPU available
    use_auth_token=HF_TOKEN
)

rag_pipeline = pipeline(
    "text2text-generation", # Changed to text2text-generation
    model=model,
    tokenizer=tokenizer
)

# -------------------------------
# Chunking function
# -------------------------------
def chunk_text(text, max_tokens=MAX_CHUNK_TOKENS):
    words = text.split()
    chunks = []
    for i in range(0, len(words), max_tokens):
        chunks.append(" ".join(words[i:i+max_tokens]))
    return chunks

# -------------------------------
# Generate RAG answer
# -------------------------------
def generate_rag_answer(query, docs, max_docs=MAX_DOCS):
    all_chunks = []
    for doc in docs[:max_docs]:
        all_chunks.extend(chunk_text(doc, MAX_CHUNK_TOKENS))

    context = "\n".join(all_chunks)
    prompt = f"Use the following context to answer the question.\n\nContext:\n{context}\n\nQuestion: {query}\nAnswer:"

    result = rag_pipeline(
        prompt,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=False
    )[0]["generated_text"]

    # Remove prompt from output
    answer = result.replace(prompt, "").strip()
    return answer

# -------------------------------
# Example query
# -------------------------------
query = "What are OECD policies about AI and governance?"
answer = generate_rag_answer(query, docs)

print("\n🔍 Query:", query)
print("\n💡 Answer:\n", answer)

# -------------------------------
# Save RAG QA results
# -------------------------------
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

rag_results = {
    "query": query,
    "answer": answer,
    "retrieved_documents": docs[:MAX_DOCS]
}

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(rag_results, f, ensure_ascii=False, indent=2)

print(f"\n✅ RAG QA results saved to {OUTPUT_PATH}")