# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQsLHA4ONKwQwCkmlUWcWyjZ0kF9d4ZB
"""

!pip uninstall pinecone-client

import sys
!{sys.executable} -m pip install -U pinecone rank_bm25 sentence-transformers tqdm

# Example corpus (you can replace this with your policy PDF chunks)
corpus = [
    "OECD report discusses global economic growth and inflation trends in 2024.",
    "The IMF policy review focuses on sustainable fiscal reforms and carbon taxation.",
    "United Nations releases climate action framework for developing countries.",
    "OECD emphasizes digital transformation and AI governance policies.",
    "The World Bank report explores inequality and global education gaps."
]

from google.colab import drive
drive.mount('/content/drive')

!pip install rank_bm25

# src/agents/retriever_agent.py

import os
import json
import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from pinecone import Pinecone, ServerlessSpec

# -------------------------------
# Paths
# -------------------------------
TASK1_JSON_PATH = "/content/drive/MyDrive/results/classical_output.json"
SBERT_EMBEDDINGS_PATH = "/content/drive/MyDrive/results/sbert_embeddings.npy"
OUTPUT_JSON_PATH = "/content/drive/MyDrive/results/retrieval_ablation.json"

# -------------------------------
# Hyperparameters
# -------------------------------
ALPHA = 0.6
TOP_K = 3  # <= 10000 for Pinecone

# -------------------------------
# Load Task 1 Output
# -------------------------------
with open(TASK1_JSON_PATH, "r", encoding="utf-8") as f:
    chunks_data = json.load(f)

texts = [chunk["original_text"] for chunk in chunks_data if chunk["original_text"].strip()]
print(f"✅ Loaded {len(texts)} chunks from Task 1.")

# -------------------------------
# Load SBERT embeddings (Task 2)
# -------------------------------
sbert_embeddings = np.load(SBERT_EMBEDDINGS_PATH, allow_pickle=True)
print(f"✅ Loaded SBERT embeddings with shape: {sbert_embeddings.shape}")

# -------------------------------
# Initialize BM25
# -------------------------------
tokenized_corpus = [doc.lower().split() for doc in texts]
bm25 = BM25Okapi(tokenized_corpus)

# -------------------------------
# Initialize Pinecone
# -------------------------------
PINECONE_API_KEY = ""  
INDEX_NAME = "rag-index"

# Create Pinecone client
pc = Pinecone(api_key=PINECONE_API_KEY)

# Create index if not exists
if INDEX_NAME not in pc.list_indexes().names():
    pc.create_index(
        name=INDEX_NAME,
        dimension=sbert_embeddings.shape[1],  # 384 for MiniLM
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )
    print("✅ Pinecone index created.")
else:
    print("ℹ️ Index already exists.")

index = pc.Index(INDEX_NAME)

# Upload embeddings if index is empty
if len(index.describe_index_stats()["namespaces"]) == 0:
    vectors = [
        {"id": str(i), "values": sbert_embeddings[i].tolist(), "metadata": {"text": texts[i]}}
        for i in range(len(texts))
    ]
    index.upsert(vectors)
    print("✅ Uploaded embeddings to Pinecone.")

# -------------------------------
# Load SBERT model once
# -------------------------------
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')

# -------------------------------
# Hybrid retrieval function
# -------------------------------
def hybrid_retrieve(query, alpha=ALPHA, top_k=TOP_K):
    # Dense vector
    dense_vec = sbert_model.encode([query])[0].tolist()
    dense_results = index.query(vector=dense_vec, top_k=top_k, include_metadata=True)
    dense_scores = {match['metadata']['text']: match['score'] for match in dense_results['matches']}

    # Sparse BM25
    tokenized_query = query.lower().split()
    sparse_scores = bm25.get_scores(tokenized_query)
    sparse_scores_dict = {texts[i]: sparse_scores[i] for i in range(len(texts))}

    # Combine scores
    combined_scores = {
        doc: alpha * dense_scores.get(doc, 0) + (1-alpha) * sparse_scores_dict.get(doc, 0)
        for doc in texts
    }

    # Top-K
    ranked = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
    return ranked

# -------------------------------
# Example query
# -------------------------------
query = "What are OECD policies about AI and governance?"
results = hybrid_retrieve(query)

print("\n🔍 Query:", query)
print("\nTop retrieved documents:\n")
for doc, score in results:
    print(f"- {doc} (score: {score:.4f})")

# -------------------------------
# Save diagnostics
# -------------------------------
os.makedirs(os.path.dirname(OUTPUT_JSON_PATH), exist_ok=True)
ablation_results = {
    "alpha": ALPHA,
    "top_k": TOP_K,
    "retrieval_results": [{"text": doc, "score": score} for doc, score in results]
}
with open(OUTPUT_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(ablation_results, f, ensure_ascii=False, indent=2)

print(f"\n✅ Retrieval diagnostics saved to {OUTPUT_JSON_PATH}")