# -*- coding: utf-8 -*-
"""summarizer_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKQtAE_Gv1dPJOvzwTgN5GekMc_Jz1Vs
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers accelerate sentence-transformers bitsandbytes
!huggingface-cli login

!pip install bitsandbytes --force-reinstall

!pip install --upgrade bitsandbytes

import os
import json
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from concurrent.futures import ThreadPoolExecutor

# --------------------------
# Paths
# --------------------------
PREPROCESSED_DOCS = "/content/drive/MyDrive/results/classical_output.json"
OUTPUT_PATH = "/content/drive/MyDrive/results/final_policy_brief.txt"

# --------------------------
# 1️⃣ Load preprocessed docs
# --------------------------
try:
    with open(PREPROCESSED_DOCS, "r", encoding="utf-8") as f:
        docs = json.load(f)
except FileNotFoundError:
    print(f"❌ ERROR: File not found at {PREPROCESSED_DOCS}")
    docs = []

# استخراج متن‌ها
texts = []
for doc in docs:
    if isinstance(doc, dict):
        texts.append(doc.get("text", "") or doc.get("content", ""))
    elif isinstance(doc, str):
        texts.append(doc)
texts = [t for t in texts if t.strip()]

# fallback برای تست
if len(texts) == 0:
    print("⚠️ No text items found. Using sample test texts.")
    texts = [
        "AI is rapidly evolving and governments are creating policies to regulate it.",
        "OECD has published guidelines for responsible AI development.",
        "Key governance implications include transparency, accountability, and ethical compliance."
    ]

print(f"✅ Loaded {len(texts)} text items")

# --------------------------
# 2️⃣ Structured Summary
# --------------------------
MODEL_SUMMARIZER = "google/flan-t5-small"
tokenizer_sum = AutoTokenizer.from_pretrained(MODEL_SUMMARIZER)
model_sum = AutoModelForSeq2SeqLM.from_pretrained(MODEL_SUMMARIZER, device_map="auto")

# ⚠️ نکته مهم: هنگام استفاده از device_map="auto" نباید device در pipeline بدهیم
summarizer = pipeline("summarization", model=model_sum, tokenizer=tokenizer_sum)

def summarize_chunk(chunk_text, idx):
    prompt = (
        f"Summarize the following OECD AI policy document in 3 sections: "
        f"[Overview], [Key Policies], [Governance Implications]. "
        f"Use clear human-readable language. Include citations like [src: file.pdf, p.{idx+1}].\n\n"
        f"{chunk_text}"
    )
    return summarizer(prompt, max_length=250, min_length=100, do_sample=False)[0]['summary_text']

# محدود کردن تعداد سند برای تست سریع و parallelization
chunks = texts[:10]
with ThreadPoolExecutor(max_workers=4) as executor:
    summaries = list(executor.map(summarize_chunk, chunks, range(len(chunks))))

structured_summary = "\n\n".join(summaries)
print("🧾 Structured Summary ready.")

# --------------------------
# 3️⃣ Simple Debate Agents
# --------------------------
def debate_agent(name, stance, summary_text):
    snippet = " ".join(summary_text.split()[:100])
    return f"{name} ({stance}):\nBased on the provided summary snippet:\n{snippet}\n\nRecommendation: " \
           f"{'Supportive AI policies are important.' if stance=='Pro-Policy' else 'Critical oversight is essential.'}"

with ThreadPoolExecutor(max_workers=2) as executor:
    future_a = executor.submit(debate_agent, "Agent A", "Pro-Policy", structured_summary)
    future_b = executor.submit(debate_agent, "Agent B", "Critical", structured_summary)
    debate_a = future_a.result()
    debate_b = future_b.result()

print("🤖 Debate Agents ready.")

# --------------------------
# 4️⃣ Consensus Policy Brief
# --------------------------
consensus_brief = (
    "🧠 Consensus Policy Brief:\n"
    "After reviewing the structured summary and considering the arguments from Agent A (Pro) and Agent B (Critical), "
    "the recommended policy approach balances supportive AI measures with critical governance concerns. "
    "Ensure that national policies follow OECD guidelines, include transparent oversight mechanisms, and address ethical implications. "
    "This policy brief merges both perspectives into actionable recommendations."
)

# --------------------------
# 5️⃣ Save Final Output
# --------------------------
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write("=== Task 5: Synthesis & Debate Results (Final Operational Version) ===\n\n")
    f.write("--- 🧾 Structured Summary ---\n" + structured_summary + "\n\n")
    f.write("--- 🤖 Agent A (Pro-Policy) ---\n" + debate_a + "\n\n")
    f.write("--- ⚙️ Agent B (Critical) ---\n" + debate_b + "\n\n")
    f.write("--- 🧠 Consensus Policy Brief ---\n" + consensus_brief)

print(f"✅ Final policy brief saved to: {OUTPUT_PATH}")

import json
import os
import re
import textwrap
from dataclasses import dataclass
from typing import List, Tuple, Optional, Dict, Any, Callable

# ---------------------------
# Citation & Summary dataclasses
# ---------------------------
@dataclass
class Citation:
    filename: str
    page: int
    def fmt(self) -> str:
        return f"[src: {os.path.basename(self.filename)}, p.{self.page}]"

@dataclass
class StructuredSummary:
    title: str
    executive_summary: str
    key_points: List[str]
    evidence: List[Dict[str, Any]]  # {"point": str, "citations": [Citation]}
    recommendations: List[str]
    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "executive_summary": self.executive_summary,
            "key_points": self.key_points,
            "evidence": [
                {"point": e["point"], "citations": [c.fmt() for c in e.get("citations", [])]}
                for e in self.evidence
            ],
            "recommendations": self.recommendations
        }

# ---------------------------
# SummarizerAgent
# ---------------------------
class SummarizerAgent:
    def __init__(self, llm_fn: Optional[Callable[[str], str]] = None):
        self.llm_fn = llm_fn

    def _extractive_summary(self, pages: List[Tuple[str, int, str]]) -> StructuredSummary:
        sentences = []
        keywords = ["policy","recommend","risk","benefit","evidence","study","regulat"]
        sent_split = re.compile(r"(?<=[.!?])\s+")
        for fname, pnum, text in pages:
            if not text.strip():
                continue
            for s in sent_split.split(text):
                s_clean = s.strip()
                if len(s_clean) < 30:
                    continue
                score = len(s_clean)
                for kw in keywords:
                    if re.search(kw, s_clean, re.IGNORECASE):
                        score += 50
                sentences.append((s_clean, Citation(fname,pnum), score))

        if not sentences:
            return StructuredSummary(
                title="No Content",
                executive_summary="No extractable text.",
                key_points=[],
                evidence=[],
                recommendations=[]
            )

        sentences.sort(key=lambda x: x[2], reverse=True)
        top_sents = sentences[:6]

        key_points = [textwrap.shorten(t[0], width=200, placeholder="...") for t in top_sents]
        evidence = [{"point": textwrap.shorten(t[0], width=400), "citations":[t[1]]} for t in top_sents]
        exec_sum = " ".join(key_points[:3])
        recs = ["Consider regulatory options; balance innovation and safety."]
        return StructuredSummary(
            title="Extractive Summary",
            executive_summary=exec_sum,
            key_points=key_points,
            evidence=evidence,
            recommendations=recs
        )

    def summarize_documents(self, pages: List[Tuple[str,int,str]]) -> StructuredSummary:
        if not pages:
            raise ValueError("No pages provided.")
        # try LLM if exists
        if self.llm_fn:
            try:
                prompt = self._build_prompt(pages)
                resp = self.llm_fn(prompt)
                data = json.loads(resp)
                evidence = []
                for e in data.get("evidence", []):
                    citations = []
                    for c in e.get("citations", []):
                        m = re.search(r"\[src:\s*([^,]+),\s*p\.?\s*(\d+)\]", c)
                        if m:
                            citations.append(Citation(m.group(1), int(m.group(2))))
                    evidence.append({"point": e.get("point",""), "citations": citations})
                return StructuredSummary(
                    title=data.get("title",""),
                    executive_summary=data.get("executive_summary",""),
                    key_points=data.get("key_points",[]),
                    evidence=evidence,
                    recommendations=data.get("recommendations",[])
                )
            except Exception as e:
                print(f"LLM summarization failed: {e}")

        # fallback extractive
        return self._extractive_summary(pages)

    def _build_prompt(self, pages: List[Tuple[str,int,str]]) -> str:
        header = ("You are a policy summarizer. Produce structured summaries "
                  "with citations like [src: filename.pdf, p.X]. Return JSON with "
                  "fields: title, executive_summary, key_points, evidence, recommendations.")
        excerpts = []
        for fname, pnum, text in pages[:12]:
            excerpts.append(f"---\nFILE: {fname} | PAGE: {pnum}\n{text[:800]}")
        return header + "\n\n" + "\n".join(excerpts) + "\n\nReturn only valid JSON."

    def save_summary(self, summary: StructuredSummary, path: str):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path,"w",encoding="utf-8") as f:
            json.dump(summary.to_dict(), f, ensure_ascii=False, indent=2)
        print(f"Saved summary to {path}")

# ---------------------------
# Demo
# ---------------------------
if __name__=="__main__":
    example_pages = [
        ("ac8b3538-en.pdf",1,"OECD discusses net-zero transition and impacts on labor demand. Policy recommendations included."),
        ("ac8b3538-en.pdf",2,"Automation risks and job displacement discussed. Evidence from OECD studies."),
        ("ch1.pdf",5,"IMF projects GDP growth and discusses regional differences and assumptions."),
    ]

    summarizer = SummarizerAgent()
    summary = summarizer.summarize_documents(example_pages)
    summarizer.save_summary(summary,"/content/drive/MyDrive/results/summary.json")
    print(summary.to_dict())