# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntNRtukm180cfcZSKhVjnGlJBFszaYSY
"""

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/NLP_project/results/classical_output.json'

if os.path.exists(file_path):
    print(f"✅ The file '{file_path}' exists in your Google Drive.")
else:
    print(f"❌ The file '{file_path}' does NOT exist in your Google Drive. Please ensure the file is present at this location and that Google Drive is mounted correctly.")

import os
import json
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, NMF
from sklearn.manifold import TSNE
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# from gensim.models import Word2Vec # Removed this line
from sentence_transformers import SentenceTransformer
import numpy as np

# Install gensim if not already installed
try:
    from gensim.models import Word2Vec # Moved this import here
except ImportError:
    !pip install gensim
    from gensim.models import Word2Vec

# -------------------------------
# Paths
# -------------------------------
TASK1_OUTPUT_PATH = "/content/drive/MyDrive/results/classical_output.json"
OUTPUT_IMAGE_PATH = "/content/drive/MyDrive/results/embedding_map.png"
os.makedirs(os.path.dirname(OUTPUT_IMAGE_PATH), exist_ok=True)

# -------------------------------
# Load Task 1 Output
# -------------------------------
with open(TASK1_OUTPUT_PATH, "r", encoding="utf-8") as f:
    chunks_data = json.load(f)
print("Sample keys in first record:", chunks_data[0].keys())


# Use 'original_text' from each chunk
texts = [chunk["original_text"] for chunk in chunks_data if chunk["original_text"].strip()]

# -------------------------------
# 1. Topic Modeling: LDA & NMF
# -------------------------------
print("Running Topic Modeling...")

# Convert text to document-term matrix
vectorizer = CountVectorizer(max_features=5000, stop_words='english')
dt_matrix = vectorizer.fit_transform(texts)

# LDA
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=10, random_state=42)
lda_topics = lda.fit_transform(dt_matrix)

# Print top words per topic
def print_top_words(model, feature_names, n_top_words=10):
    for topic_idx, topic in enumerate(model.components_):
        message = f"Topic #{topic_idx}: "
        message += " ".join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)

print("\nLDA Topics:")
print_top_words(lda, vectorizer.get_feature_names_out())

# NMF
tfidf_vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

nmf = NMF(n_components=10, random_state=42)
nmf_topics = nmf.fit_transform(tfidf_matrix)

print("\nNMF Topics:")
print_top_words(nmf, tfidf_vectorizer.get_feature_names_out())

