# -*- coding: utf-8 -*-
"""verifier_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3CzLLb2-VfBXMsIUh9GyFUS8kPsef8F
"""

from google.colab import drive
drive.mount('/content/drive')

from __future__ import annotations
import os
import re
import json
import math
import logging
from datetime import datetime
from collections import Counter
from typing import List, Tuple, Optional, Callable, Dict, Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------
# Utilities
# ---------------------------
def _ensure_results_dir(path: str = "results"):
    if path and not os.path.exists(path):
        os.makedirs(path, exist_ok=True)

def _save_metrics(metrics: Dict[str, Any], path: str = "/content/drive/MyDrive/NLP_progect/metrics.json") -> str:
    _ensure_results_dir(os.path.dirname(path) or "results")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, ensure_ascii=False, indent=2)
    logger.info("Saved verification metrics to %s", path)
    return path

def _cosine(u: List[float], v: List[float]) -> float:
    if not u or not v:
        return 0.0
    dot = sum(a*b for a,b in zip(u,v))
    nu = math.sqrt(sum(a*a for a in u))
    nv = math.sqrt(sum(b*b for b in v))
    if nu==0 or nv==0: return 0.0
    return dot/(nu*nv)

def _simple_bow_embed(text: str, top_k: int=200) -> List[float]:
    tokens = re.findall(r"\b[a-zA-Z]{3,}\b", text.lower())
    if not tokens: return []
    counts = Counter(tokens)
    items = sorted(counts.items(), key=lambda x:(-x[1], x[0]))[:top_k]
    vec = [float(c) for _,c in items]
    norm = math.sqrt(sum(x*x for x in vec)) or 1.0
    return [x/norm for x in vec]

def _extract_dates(text: str) -> List[datetime]:
    dates = []
    for m in re.findall(r"\b(20\d{2}|19\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])\b", text):
        try: dates.append(datetime.fromisoformat("-".join(m)))
        except: pass
    for m in re.findall(r"\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(20\d{2}|19\d{2})\b", text, re.IGNORECASE):
        try: dates.append(datetime.strptime(f"{m[0]} {m[1]}", "%B %Y"))
        except: pass
    return dates

# ---------------------------
# VerifierAgent
# ---------------------------
class VerifierAgent:
    def __init__(
        self,
        nli_fn: Optional[Callable[[str,str],Dict[str,Any]]] = None,
        embed_fn: Optional[Callable[[List[str]], List[List[float]]]] = None,
        sim_threshold: float = 0.8
    ):
        self.nli_fn = nli_fn
        self.embed_fn = embed_fn
        self.sim_threshold = sim_threshold

    def _nli_check(self, premise: str, hypothesis: str) -> Dict[str,Any]:
        if self.nli_fn:
            try:
                res = self.nli_fn(premise, hypothesis)
                return {"label": res.get("label","NEUTRAL").upper(), "score": float(res.get("score",0.0))}
            except Exception as e:
                logger.exception("nli_fn failed: %s", e)
        # fallback heuristic
        hyp = hypothesis.lower()
        neg_words = ["not","no","never","n't","without"]
        neg = any(w in hyp for w in neg_words)
        overlap = len(set(re.findall(r"\b[a-zA-Z]{3,}\b", premise.lower())).intersection(
                      set(re.findall(r"\b[a-zA-Z]{3,}\b", hyp))
                  ))
        if neg and overlap>3: return {"label":"CONTRADICTION","score":0.6}
        if overlap>=5: return {"label":"ENTAILMENT","score":min(0.95,0.2+0.15*overlap)}
        return {"label":"NEUTRAL","score":0.5}

    def _embed_texts(self, texts: List[str]) -> List[List[float]]:
        if self.embed_fn:
            try:
                return self.embed_fn(texts)
            except Exception as e:
                logger.exception("embed_fn failed: %s", e)
        return [_simple_bow_embed(t) for t in texts]

    def _semantic_alignment(self, claim:str, evidence:str) -> float:
        emb_c, emb_e = self._embed_texts([claim, evidence])
        if not emb_c or not emb_e: return 0.0
        L = max(len(emb_c), len(emb_e))
        emb_c += [0.0]*(L-len(emb_c))
        emb_e += [0.0]*(L-len(emb_e))
        return _cosine(emb_c, emb_e)

    def _temporal_consistency(self, claim:str, evidence_texts:List[str], reference_date:Optional[str]=None) -> Dict[str,Any]:
        claim_dates = _extract_dates(claim)
        ev_dates = []
        for t in evidence_texts: ev_dates.extend(_extract_dates(t))
        ref_dt = None
        if reference_date:
            try: ref_dt = datetime.fromisoformat(reference_date)
            except: ref_dt = None
        consistent = True
        issues = []
        for cd in claim_dates:
            latest_ref = ref_dt
            if ev_dates: latest_ref = max(ev_dates) if not latest_ref else max(latest_ref,max(ev_dates))
            if latest_ref and cd>latest_ref:
                consistent=False
                issues.append(f"Claim date {cd.date()} is later than evidence/reference {latest_ref.date()}")
        return {"claim_dates":[d.isoformat() for d in claim_dates],
                "evidence_dates":[d.isoformat() for d in ev_dates],
                "reference_date": ref_dt.isoformat() if ref_dt else None,
                "consistent": consistent,
                "issues": issues}

    def verify_claims(self, claims:List[str], evidences:List[Tuple[str,int,str]], reference_date:Optional[str]=None) -> Dict[str,Any]:
        if not claims: raise ValueError("No claims provided")
        results = {"per_claim":[], "aggregated":{}}
        total, entail, contra, neutral, sim_ok, sim_total = 0,0,0,0,0,0
        evidence_texts = [t for _,_,t in evidences]
        concatenated = "\n\n".join(evidence_texts) if evidence_texts else ""
        for claim in claims:
            total+=1
            nli = self._nli_check(concatenated, claim)
            lbl = nli["label"]
            if lbl.startswith("ENT"): entail+=1
            if lbl.startswith("CON"): contra+=1
            if lbl.startswith("NEU"): neutral+=1
            best_sim=0.0
            best_idx=None
            for idx,(_,_,txt) in enumerate(evidences):
                sim = self._semantic_alignment(claim, txt)
                sim_total+=1
                if sim>=self.sim_threshold: sim_ok+=1
                if sim>best_sim:
                    best_sim=sim
                    best_idx=idx
            temporal = self._temporal_consistency(claim, evidence_texts, reference_date)
            results["per_claim"].append({
                "claim": claim,
                "nli": nli,
                "best_similarity": best_sim,
                "best_evidence_index": best_idx,
                "temporal": temporal
            })
        agg = {
            "total_claims":total,
            "entailment":entail,
            "contradiction":contra,
            "neutral":neutral,
            "similarity_threshold":self.sim_threshold,
            "sim_ok_count":sim_ok,
            "sim_total_checks":sim_total
        }
        results["aggregated"]=agg
        try: _save_metrics({"verifier":agg})
        except Exception as e: logger.exception("Failed to save metrics: %s", e)
        return results

# ---------------------------
# Demo / test
# ---------------------------
if __name__=="__main__":
    demo_claims = [
        "OECD report predicts labor demand increase by 2024.",
        "Vaccination coverage increased by 5% in 2023."
    ]
    demo_evidences = [
        ("Data/tdr2024_en.pdf", 3, "In 2023 vaccination coverage rose by approximately five percentage points."),
        ("Data/ch1.pdf", 2, "OECD Employment Outlook 2024 discusses net-zero transition and labor demand.")
    ]
    agent = VerifierAgent()
    res = agent.verify_claims(demo_claims, demo_evidences, reference_date="2024-12-31")
    print(json.dumps(res, indent=2, ensure_ascii=False))