# -*- coding: utf-8 -*-
"""visualizer_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XY_9d-C0qhxbhUaypRrf2fDJMTSUe4bS
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import json
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt

try:
    import networkx as nx
    HAS_NETWORKX = True
except ImportError:
    print("NetworkX not available. Agent graph plotting disabled.")
    HAS_NETWORKX = False
    nx = None

# ---------------- Paths ----------------
RESULTS_DIR = Path("/content/drive/MyDrive/results")
MEMORY_PATH = RESULTS_DIR / "memory.json"
PLOTS_DIR = RESULTS_DIR / "plots"
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

# ---------------- Utilities ----------------
def _load_json(path: Path):
    if not path.exists():
        return {"records": []}
    try:
        with path.open("r", encoding="utf-8") as fh:
            return json.load(fh)
    except json.JSONDecodeError:
        print(f"Warning: failed to parse {path}")
        return {"records": []}

# ---------------- Plot functions ----------------
def plot_confidence_trajectory(memory, out_path: Path):
    records = memory.get("records", [])
    if not records:
        print("No records to plot confidence trajectory.")
        return
    df = pd.DataFrame(records)
    if "ts" not in df or "confidence" not in df:
        print("Missing ts or confidence in memory; skipping trajectory.")
        return
    df["ts"] = pd.to_datetime(df["ts"], unit="s")
    df = df.sort_values("ts")
    plt.figure(figsize=(10, 4))
    plt.plot(df["ts"], df["confidence"], marker="o", linewidth=1)
    plt.title("Confidence Trajectory Over Time")
    plt.xlabel("Time")
    plt.ylabel("Confidence")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()
    print("Saved confidence trajectory to", out_path)

def build_agent_graph(memory):
    if not HAS_NETWORKX:
        return None
    G = nx.DiGraph()
    records = memory.get("records", [])
    edges = []
    for r in records:
        extra = r.get("extra", {})
        calls = extra.get("agent_calls", [])
        for e in calls:
            frm, to = e.get("from"), e.get("to")
            if frm and to:
                edges.append((frm, to))
    if edges:
        G.add_edges_from(edges)
    else:
        nodes = [
            "PDFIngestionAgent", "PreprocessorAgent", "TopicModelAgent",
            "EmbeddingAgent", "RetrieverAgent", "PlannerAgent", "SummarizerAgent",
            "VerifierAgent", "EvaluatorAgent", "MemoryAgent", "VisualizerAgent"
        ]
        G.add_nodes_from(nodes)
        fallback_edges = [
            ("PDFIngestionAgent", "PreprocessorAgent"),
            ("PreprocessorAgent", "TopicModelAgent"),
            ("TopicModelAgent", "EmbeddingAgent"),
            ("EmbeddingAgent", "RetrieverAgent"),
            ("RetrieverAgent", "PlannerAgent"),
            ("PlannerAgent", "SummarizerAgent"),
            ("SummarizerAgent", "VerifierAgent"),
            ("VerifierAgent", "EvaluatorAgent"),
            ("EvaluatorAgent", "MemoryAgent"),
        ]
        G.add_edges_from(fallback_edges)
    return G

def plot_agent_graph(G, out_path: Path):
    if not HAS_NETWORKX or G is None:
        print("No graph to plot.")
        return
    plt.figure(figsize=(10, 8))
    pos = nx.spring_layout(G, k=0.6, seed=42)
    nx.draw_networkx_nodes(G, pos, node_size=900, node_color="#8fbfe0")
    nx.draw_networkx_edges(G, pos, arrowstyle="-|>", arrowsize=12, width=1.8)
    nx.draw_networkx_labels(G, pos, font_size=9)
    plt.title("Agent Graph")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()
    print("Saved agent graph to", out_path)

# ---------------- Main ----------------
def main():
    memory = _load_json(MEMORY_PATH)

    # Plot confidence trajectory
    plot_confidence_trajectory(memory, PLOTS_DIR / "confidence_trajectory.png")

    # Build and plot agent graph
    G = build_agent_graph(memory)
    plot_agent_graph(G, PLOTS_DIR / "agent_graph.png")

    # Optional: summary
    df = pd.DataFrame(memory.get("records", []))
    if not df.empty and "confidence" in df.columns:
        print(f"Mean confidence: {df['confidence'].dropna().mean():.3f}")
    else:
        print("No confidence stats available.")

if __name__ == "__main__":
    main()